apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "worker"
  name: 99-worker-azure
spec:
  osImageURL: quay.io/jcallen/ocp-azure-agent-layer@sha256:3530ad1beee0bad63b6a8504e4392d56cf61f8d88f3836de0b9b80e1186005d7
