kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ocp-azure-agent-layer
  namespace: jcallen-azure-agent
  labels:
    build: ocp-azure-agent-layer
spec:
  lookupPolicy:
    local: false
